/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package userInterface.sensor;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.NGOEnterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.person.Patients;
import Business.userAccount.UserAccount;
import Business.workQueue.NeedSensorDeviceWorkRequest;
import Business.workQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author shivanisahu
 */
public class ManageVitalSignJPanel extends javax.swing.JPanel {
     
    private JPanel userProcessContainer;
    private UserAccount userAccount; 
    private Patients person;
    private EcoSystem ecoSystem;

    public ManageVitalSignJPanel(JPanel userProcessContainer, UserAccount userAccount, EcoSystem ecoSystem) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.userAccount = userAccount;
        person = (Patients)userAccount.getPerson();
        this.ecoSystem = ecoSystem;
        vitalSignPanel.setVisible(false);

    }
    
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        Graphics2D g2d = (Graphics2D) g;
        g2d.setRenderingHint(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_QUALITY);
        int w = getWidth();
        int h = getHeight();
        
        Color c1 = new Color(0,255,204);
        Color c2 = Color.white;
     
        GradientPaint gp = new GradientPaint(w/4, 0, c2, w/4, h, c1);
        setOpaque( false );
        g2d.setPaint(gp);
        g2d.fillRect(0, 0, w, h);
        setOpaque( true );
    }
    
   /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        shareInfoGroup = new javax.swing.ButtonGroup();
        hasSensorGroup = new javax.swing.ButtonGroup();
        getAlertsGroup = new javax.swing.ButtonGroup();
        hasTumorProblemGroup = new javax.swing.ButtonGroup();
        sendToDoctorGroup = new javax.swing.ButtonGroup();
        getAlertFromRelief = new javax.swing.JLabel();
        shareVitalInfoJRadioYes = new javax.swing.JRadioButton();
        shareVitalInfoJRadioNo = new javax.swing.JRadioButton();
        shareInfo = new javax.swing.JLabel();
        submitVitalSignsJBtn = new javax.swing.JButton();
        cancelJBtn = new javax.swing.JButton();
        vitalSignPanel = new javax.swing.JPanel();
        hasSensorRadioYes = new javax.swing.JRadioButton();
        oxygenRateCheckBox = new javax.swing.JCheckBox();
        getAlertJRadioYes = new javax.swing.JRadioButton();
        sysBPCheckBox = new javax.swing.JCheckBox();
        weightCheckBox = new javax.swing.JCheckBox();
        getAlert = new javax.swing.JLabel();
        sensorDevice = new javax.swing.JLabel();
        getAlertJRadioNo = new javax.swing.JRadioButton();
        vitalSignsTrck = new javax.swing.JLabel();
        hasSensorRadioNo = new javax.swing.JRadioButton();
        pulseRateChckBox = new javax.swing.JCheckBox();
        backJButton = new javax.swing.JButton();
        tumorProblems = new javax.swing.JLabel();
        hasTumorYes = new javax.swing.JRadioButton();
        hasTumorRadioNo = new javax.swing.JRadioButton();

        getAlertFromRelief.setFont(new java.awt.Font("Malayalam MN", 3, 24)); // NOI18N
        getAlertFromRelief.setText("Vital Signs Manage Panel");

        shareInfoGroup.add(shareVitalInfoJRadioYes);
        shareVitalInfoJRadioYes.setText("Yes");
        shareVitalInfoJRadioYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shareVitalInfoJRadioYesActionPerformed(evt);
            }
        });

        shareInfoGroup.add(shareVitalInfoJRadioNo);
        shareVitalInfoJRadioNo.setText("No");
        shareVitalInfoJRadioNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shareVitalInfoJRadioNoActionPerformed(evt);
            }
        });

        shareInfo.setText("Would you like to share Vital Sign details:");

        submitVitalSignsJBtn.setText("Done");
        submitVitalSignsJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitVitalSignsJBtnActionPerformed(evt);
            }
        });

        cancelJBtn.setText("Cancel");

        vitalSignPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        hasSensorGroup.add(hasSensorRadioYes);
        hasSensorRadioYes.setText("Yes");
        hasSensorRadioYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasSensorRadioYesActionPerformed(evt);
            }
        });

        oxygenRateCheckBox.setText("Oxygen Rate");

        getAlertsGroup.add(getAlertJRadioYes);
        getAlertJRadioYes.setText("Yes");
        getAlertJRadioYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getAlertJRadioYesActionPerformed(evt);
            }
        });

        sysBPCheckBox.setText("Blood Pressure");

        weightCheckBox.setText("Weight");

        getAlert.setText("Would you like to get alert from Relief:");

        sensorDevice.setText("Do you have Optune?");

        getAlertsGroup.add(getAlertJRadioNo);
        getAlertJRadioNo.setText("No");
        getAlertJRadioNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getAlertJRadioNoActionPerformed(evt);
            }
        });

        vitalSignsTrck.setText("Select Vital Signs you would like to track:");

        hasSensorGroup.add(hasSensorRadioNo);
        hasSensorRadioNo.setText("No");
        hasSensorRadioNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasSensorRadioNoActionPerformed(evt);
            }
        });

        pulseRateChckBox.setText("Pulse Rate");

        javax.swing.GroupLayout vitalSignPanelLayout = new javax.swing.GroupLayout(vitalSignPanel);
        vitalSignPanel.setLayout(vitalSignPanelLayout);
        vitalSignPanelLayout.setHorizontalGroup(
            vitalSignPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vitalSignPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(vitalSignPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vitalSignsTrck, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sensorDevice, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(getAlert))
                .addGap(58, 58, 58)
                .addGroup(vitalSignPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(weightCheckBox)
                    .addComponent(sysBPCheckBox)
                    .addGroup(vitalSignPanelLayout.createSequentialGroup()
                        .addComponent(getAlertJRadioYes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(getAlertJRadioNo))
                    .addGroup(vitalSignPanelLayout.createSequentialGroup()
                        .addComponent(hasSensorRadioYes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(hasSensorRadioNo))
                    .addComponent(oxygenRateCheckBox)
                    .addComponent(pulseRateChckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        vitalSignPanelLayout.setVerticalGroup(
            vitalSignPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vitalSignPanelLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(vitalSignPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sensorDevice)
                    .addGroup(vitalSignPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(hasSensorRadioYes)
                        .addComponent(hasSensorRadioNo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(vitalSignPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vitalSignsTrck)
                    .addComponent(pulseRateChckBox))
                .addGap(18, 18, 18)
                .addComponent(oxygenRateCheckBox)
                .addGap(18, 18, 18)
                .addComponent(sysBPCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(weightCheckBox)
                .addGap(21, 21, 21)
                .addGroup(vitalSignPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(getAlert)
                    .addComponent(getAlertJRadioYes)
                    .addComponent(getAlertJRadioNo))
                .addGap(53, 53, 53))
        );

        backJButton.setText("Previous");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        tumorProblems.setText("Do you have Tumor symptoms ");

        hasTumorProblemGroup.add(hasTumorYes);
        hasTumorYes.setText("Yes");
        hasTumorYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasTumorYesActionPerformed(evt);
            }
        });

        hasTumorProblemGroup.add(hasTumorRadioNo);
        hasTumorRadioNo.setText("No");
        hasTumorRadioNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasTumorRadioNoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(vitalSignPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(backJButton)
                        .addGap(268, 268, 268)
                        .addComponent(submitVitalSignsJBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cancelJBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(365, 365, 365)
                                        .addComponent(hasTumorYes))
                                    .addComponent(tumorProblems))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(hasTumorRadioNo))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(shareInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(shareVitalInfoJRadioYes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(shareVitalInfoJRadioNo))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addComponent(getAlertFromRelief, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(373, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(getAlertFromRelief)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shareVitalInfoJRadioYes)
                    .addComponent(shareVitalInfoJRadioNo)
                    .addComponent(shareInfo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tumorProblems)
                        .addGap(9, 9, 9))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(hasTumorYes)
                        .addComponent(hasTumorRadioNo)))
                .addGap(18, 18, 18)
                .addComponent(vitalSignPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backJButton)
                    .addComponent(cancelJBtn)
                    .addComponent(submitVitalSignsJBtn))
                .addGap(41, 41, 41))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void submitVitalSignsJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitVitalSignsJBtnActionPerformed
      
        try
        {
        if(shareInfoGroup.getSelection() == null || hasTumorProblemGroup.getSelection() == null)
       {
      JOptionPane.showMessageDialog(null, "Select radio button to let us know if you would like to share Information ","warning", JOptionPane.WARNING_MESSAGE);
       return;      
       }
       
       if(shareVitalInfoJRadioYes.isSelected() && hasTumorYes.isSelected())
       {
        person.setShareVitalInfo(true);
        person.setHasTumorProblem(true);
           
         boolean hR =  false;
         boolean bp = false;
         boolean rr = false;
         boolean wght = false;
            
      ArrayList<String> vitalSigns = new ArrayList<>();
        if(pulseRateChckBox.isSelected())
        {
        hR=true;    
        vitalSigns.add(pulseRateChckBox.getText());
        }
        if(sysBPCheckBox.isSelected())
        {
            bp = true;
          vitalSigns.add(sysBPCheckBox.getText());   
        }
        if(oxygenRateCheckBox.isSelected())
        {
            rr = true;
          vitalSigns.add(oxygenRateCheckBox.getText());   
        }
         if(weightCheckBox.isSelected())
        {
            wght = true;
          vitalSigns.add(weightCheckBox.getText());   
        }
       if(!hR || !bp || !rr || !wght)
         {
        JOptionPane.showMessageDialog(null, "Select all the Checkboxes to track Vital signs","warning", JOptionPane.WARNING_MESSAGE);
         return;      
        }
        
         person.setVitalSignTrackList(vitalSigns);
       }
       if(hasSensorGroup.getSelection() == null)
       {
       JOptionPane.showMessageDialog(null, "Select a radio button to let us know if you have a optune device ","warning", JOptionPane.WARNING_MESSAGE);
       return;        
       }
      
       if(getAlertsGroup.getSelection() == null)
       {
       JOptionPane.showMessageDialog(null, "Select a radio button to let us know if you would like to get alerts ","warning", JOptionPane.WARNING_MESSAGE);
       return;     
       }
     // To add vital sign data  
     if(person.isShareVitalInfo() && person.isHasSensorDevice())
     {
        person.setHasSensorDevice(true);
        person.addVitalSign();    
      }
       JOptionPane.showMessageDialog(null, "Successfully updated Vital Sign information","success", JOptionPane.PLAIN_MESSAGE);
       
       if(person.isShareVitalInfo() && !person.isHasSensorDevice())
       {
        person.setHasSensorDevice(false);
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(this, "Do you need a optune ? ", "warning",dialogButton);
        if(dialogResult == JOptionPane.YES_OPTION)
        {
            
        if(!(userAccount.getWorkQueue().getWorkRequestList().isEmpty()))
                {
                for(WorkRequest request : userAccount.getWorkQueue().getWorkRequestList())
                {
                   if(request.getMessage().equalsIgnoreCase("Need Sensor Device"))
                   {
                JOptionPane.showMessageDialog(null, "You have placed a request for optune device earlier ","warning", JOptionPane.WARNING_MESSAGE);
                 return;              
                   }
                }
                }    
            
        String message = "Need Sensor Device";    
        NeedSensorDeviceWorkRequest nsdwr = new NeedSensorDeviceWorkRequest();
        nsdwr.setMessage("Need Sensor Device");
        nsdwr.setComments(message);
        nsdwr.setSender(userAccount);
        nsdwr.setStatus("Sent");
        
      try
      {
        for(Network network : ecoSystem.getNetworkList())
        {
          for(Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList())
          {
              if(enterprise instanceof NGOEnterprise)
              {
              if(enterprise.getOrganizationDirectory().getOrganizationList().isEmpty())
              {
             JOptionPane.showMessageDialog(null, "Donor Organization in NGO Enterprise does not exist as of now ","warning", JOptionPane.WARNING_MESSAGE);
             return;       
              }
              for(Organization org : enterprise.getOrganizationDirectory().getOrganizationList())
              {
              org.getWorkQueue().getWorkRequestList().add(nsdwr);
              }
             }
          }
        }
      }
      catch(NullPointerException npe)
      {
       JOptionPane.showMessageDialog(null, "NGO Enterprise does not exist as of now ","warning", JOptionPane.WARNING_MESSAGE);
        return;          
      }
        userAccount.getWorkQueue().getWorkRequestList().add(nsdwr);
        JOptionPane.showMessageDialog(null, "Request created successfully", "success", JOptionPane.PLAIN_MESSAGE);
         
        }
        resetFields();
        }
        }
        catch(Exception e)
        {
      JOptionPane.showMessageDialog(null, "Enter details in all fields  ","warning", JOptionPane.WARNING_MESSAGE);
         return;    
        }
       
    }//GEN-LAST:event_submitVitalSignsJBtnActionPerformed
    
    public void  resetFields()
    {
        hasTumorYes.setSelected(false);
        hasTumorRadioNo.setSelected(false);
        shareVitalInfoJRadioNo.setSelected(false);
        shareVitalInfoJRadioYes.setSelected(false);
        hasSensorRadioYes.setSelected(false);
        hasSensorRadioNo.setSelected(false);
        pulseRateChckBox.setSelected(false);
        oxygenRateCheckBox.setSelected(false);
        sysBPCheckBox.setSelected(false);
        weightCheckBox.setSelected(false);
        getAlertJRadioYes.setSelected(false);
        getAlertJRadioNo.setSelected(false);
    }
       

    private void shareVitalInfoJRadioYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shareVitalInfoJRadioYesActionPerformed
         
         person.setShareVitalInfo(true);
         if(hasTumorYes.isSelected())
         {
           vitalSignPanel.setVisible(true);   
         }
           
    }//GEN-LAST:event_shareVitalInfoJRadioYesActionPerformed

    private void shareVitalInfoJRadioNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shareVitalInfoJRadioNoActionPerformed
         person.setShareVitalInfo(false);
         vitalSignPanel.setVisible(false);
    }//GEN-LAST:event_shareVitalInfoJRadioNoActionPerformed

    private void hasSensorRadioYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasSensorRadioYesActionPerformed
       person.setHasSensorDevice(true);
       
    }//GEN-LAST:event_hasSensorRadioYesActionPerformed

    private void hasSensorRadioNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasSensorRadioNoActionPerformed
        person.setHasSensorDevice(false);
    }//GEN-LAST:event_hasSensorRadioNoActionPerformed

    private void getAlertJRadioYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getAlertJRadioYesActionPerformed
       person.setGetAlerts(true);
    }//GEN-LAST:event_getAlertJRadioYesActionPerformed

    private void getAlertJRadioNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getAlertJRadioNoActionPerformed
        person.setGetAlerts(false);
    }//GEN-LAST:event_getAlertJRadioNoActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
         userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void hasTumorYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasTumorYesActionPerformed
        person.setHasTumorProblem(true);
        if(shareVitalInfoJRadioYes.isSelected())
        {
        vitalSignPanel.setVisible(true);
        }
    }//GEN-LAST:event_hasTumorYesActionPerformed

    private void hasTumorRadioNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasTumorRadioNoActionPerformed
       person.setHasTumorProblem(false);
        vitalSignPanel.setVisible(false);
    }//GEN-LAST:event_hasTumorRadioNoActionPerformed
  
    
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton cancelJBtn;
    private javax.swing.JLabel getAlert;
    private javax.swing.JLabel getAlertFromRelief;
    private javax.swing.JRadioButton getAlertJRadioNo;
    private javax.swing.JRadioButton getAlertJRadioYes;
    private javax.swing.ButtonGroup getAlertsGroup;
    private javax.swing.ButtonGroup hasSensorGroup;
    private javax.swing.JRadioButton hasSensorRadioNo;
    private javax.swing.JRadioButton hasSensorRadioYes;
    private javax.swing.ButtonGroup hasTumorProblemGroup;
    private javax.swing.JRadioButton hasTumorRadioNo;
    private javax.swing.JRadioButton hasTumorYes;
    private javax.swing.JCheckBox oxygenRateCheckBox;
    private javax.swing.JCheckBox pulseRateChckBox;
    private javax.swing.ButtonGroup sendToDoctorGroup;
    private javax.swing.JLabel sensorDevice;
    private javax.swing.JLabel shareInfo;
    private javax.swing.ButtonGroup shareInfoGroup;
    private javax.swing.JRadioButton shareVitalInfoJRadioNo;
    private javax.swing.JRadioButton shareVitalInfoJRadioYes;
    private javax.swing.JButton submitVitalSignsJBtn;
    private javax.swing.JCheckBox sysBPCheckBox;
    private javax.swing.JLabel tumorProblems;
    private javax.swing.JPanel vitalSignPanel;
    private javax.swing.JLabel vitalSignsTrck;
    private javax.swing.JCheckBox weightCheckBox;
    // End of variables declaration//GEN-END:variables

 
}
